### ISSUE TITLE
启动失败：GLIBC_2.32 not found

### ISSUE THREAD

**Issue by xtremforce** [aoyouer/selfhelp-iptables#12]
新版本启动失败：

`/selfhelp-iptables: /lib64/libc.so.6: version 'GLIBC_2.32' not found (required by ...)`

CentOS 8，已经通过 dnf update glibc-devel 到最新。目前最新只有 2.28。网上查了下，似乎需要手工下载 glibc 源码编译新版本，但如果机器比较多，一个个去编译安装不方便。

**我问了下 ChatGPT 的回答：**

如果您无法升级或安装 GNU C 库，则可以考虑将 GO 应用程序编译为静态二进制文件。这样，您的应用程序将包含所有必要的库文件，不需要在运行时从系统中加载。要将 GO 应用程序编译为静态二进制文件，请使用以下命令：

`go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o your-binary-name your-source-file.go`

将 "your-binary-name" 替换为您的二进制文件名称，将 "your-source-file.go" 替换为您的 GO 源代码文件。

**Comment by haojie06** [comment]
我刚才重新构建了一次，关闭了cgo，你再下最新的release的文件看看吧

**Comment by xtremforce** [comment]
现在可以运行了！


另外，建议软件在启动时检查 root 权限，非 root 提示错误。

**Comment by xtremforce** [comment]
新版本又出现这个 `GLIBC_2.32' not found 的问题了。
