### ISSUE TITLE
Readme部分文字不理解其含义

### ISSUE THREAD

**Issue by fengguowudi** [aoyouer/selfhelp-iptables#13]
不会默认为http api端口添加白名单，所以可以使用 -p [http api 监听的端口] 来阻止外部直接请求http api(必须走反向代理)

-p httpapi端口之后 反代不也无法请求了吗？
而且反代和不反代，访问方式不是一样的吗？还是说反代只是为了加个域名或者套个cdn

**Comment by xtremforce** [comment]
反代可以加 HTTPS，可以隐藏掉该服务端口的存在，还能与其他网站共用 80 / 443 端口等等。
似乎程序默认允许 127.0.0.1 访问到，所以反代可以正常。

**Comment by haojie06** [comment]
反代的话，会自动添加本机的ip到白名单中，所以你只要保证你的用于反代的服务的端口可以访问就可以了。
