### ISSUE TITLE
端口号配置有 bug

### ISSUE THREAD

**Issue by xtremforce** [aoyouer/selfhelp-iptables#14]
更新：似乎是没用 root 权限启动引起的。建议软件在启动时检查权限，非 root 提示错误。

参数 -p 端口1 端口2 的方式似乎无效？

`selfhelp-iptables start -l 8888 -u user -a password **-p 8888 1234** --reverse`
这样，运行结果：
```
enable reverse proxy support
protected ports: [8888] whitelisted ports: []
whitelisted ips: []
```
这种写法似乎仅读取到第一个端口号。实际没保护到 1234，而且 8888 也依然能被直接访问。

而当我改成 
selfhelp-iptables start -l 8888 -u user -a password **-p 8888 -p 1234** --reverse
结果为：
```
enable reverse proxy support
protected ports: [8888 1234] whitelisted ports: []
whitelisted ips: []
```
虽然日志上显示保护了 2 个端口，但实际上，8888 依然能被外界直接访问到。

**Comment by haojie06** [comment]
这里是我文档写错了，多个端口还是得使用多个flag指定，已经更新了
