### ISSUE TITLE
新版本又出现 GLIBC 错误

### ISSUE THREAD

**Issue by xtremforce** [aoyouer/selfhelp-iptables#17]
/selfhelp-iptables: /lib64/libc.so.6: version `GLIBC_2.32' not found
/selfhelp-iptables: /lib64/libc.so.6: version `GLIBC_2.34' not found

OS: CentOS8

**Comment by haojie06** [comment]
请从release重新下载一次看看，我重新构建了一个版本

**Comment by xtremforce** [comment]
可以了
