### ISSUE TITLE
是否能增加动态加载配置文件功能？

### ISSUE THREAD

**Issue by lizs365** [aoyouer/selfhelp-iptables#19]
首先感谢作者分享此项目，针对个人小范围使用的服务端口保护或内网穿透端口保护非常有用。

使用过程中碰到一个问题，修改了配置文件（比如增加了新端口）重启程序后已有的白名单IP会被清空重置，
需要访问被保护端口的地方都需要重新添加一次白名单，是否计划增加一个动态加载配置文件功能，这样新
增端口后可以生效也不会清空内存中的白名单，或增加一个url命令可以手动触发重新加载配置文件而不清内
存中的白名单？谢谢。

**Comment by haojie06** [comment]
这个程序我太久没看了，重新修改需要一些时间，这段时间我又比较忙，所以可能最近都没时间弄这个，不好意思了

**Comment by haojie06** [comment]
不过我也许可以做一个添加白名单后将ip写回到配置文件的修改

**Comment by haojie06** [comment]
试试 https://github.com/haojie06/selfhelp-iptables/releases/download/2.4.4-beta.1/selfhelp_iptables ，在使用配置文件的情况下，添加的白名单会记录到配置文件的whitelistedips中

**Comment by lizs365** [comment]
谢谢勤劳的作者，已测试，白名单IP添加时会自动回写到配置文件，
现在可以放心的修改内容重启了，再次感谢
