### ISSUE TITLE
问个参数问题

### ISSUE THREAD

**Issue by fengguowudi** [aoyouer/selfhelp-iptables#2]
--reverse 开启反向代理支持，读取http请求头获取客户端ip，请仅在使用可信反向代理的情况下使用,nginx示例:
这个反向代理是指什么呢，反代网页吗？能简单说明下吗

**Comment by haojie06** [comment]
这个反向代理指的是如果你希望对api的请求安全一些，可以在使用配合nginx或者caddy通过https的请求来添加白名单，请求由nginx或者caddy转发到这个程序的端口上。
