### ISSUE TITLE
是否考虑更换目前的防火墙程序

### ISSUE THREAD

**Issue by fengguowudi** [aoyouer/selfhelp-iptables#3]
最近nftables 这个据说比iptables好

**Comment by haojie06** [comment]
其实iptables 和 nftables 都是运行在用户空间用来控制内核的netfilter的工具，实际上防火墙是通过netfilter实现的。所以效果应该没太大区别，主要是配置方式的差异。不过之后我有空的话考虑重新写一下这个程序。

**Comment by fengguowudi** [comment]
大佬有时间了吗？

**Comment by haojie06** [comment]
上半年都没什么时间，不过为啥一定要nftables呢，nftables和iptables是可以共存的呀
