### ISSUE TITLE
systemd service启动程序，CPU占用100%

### ISSUE THREAD

**Issue by styxiik** [aoyouer/selfhelp-iptables#4]
由于shell启动程序后关掉似乎会停止程序，也为了方便开机启动，自己写了一个service启动，但是启动后cpu占用一直维持100%，在三台vps上皆如此，手动命令不会出现该问题。
系统：ubuntu 20
vps：甲骨文
相关：ufw开启（尝试关闭ufw再systemctl启动，无改善）
service配置如下：
[Unit]

Description=whitelist

After=network.target

[Service]

Type=simple

ExecStart= /root/selfhelp-iptables start -u 用户密码 -a 管理密码 -l web端口 -p 白名单管理端口 -r w --trigger 10/3

Restart=always

PrivateTmp=true

[Install]

WantedBy=multi-user.target

<img width="598" alt="image" src="https://user-images.githubusercontent.com/84225473/172037378-ad37be5e-4ae5-4247-b84f-7b3b20abe184.png">

**Comment by haojie06** [comment]
因为我这个程序尝试读取了stdin输入来获取用户输入，但是在systemd里面并不存在stdin，不断调用导致高占用。
你可以在service文件里面加上下面几行重定向输入和输出
```
StandardInput=tty
StandardOutput=tty
StandardError=null
TTYPath=/dev/tty12 
```

**Comment by styxiik** [comment]
> 因为我这个程序尝试读取了stdin输入来获取用户输入，但是在systemd里面并不存在stdin，不断调用导致高占用。 你可以在service文件里面加上下面几行重定向输入和输出
> 
> ```
> StandardInput=tty
> StandardOutput=tty
> StandardError=null
> TTYPath=/dev/tty12 
> ```

感谢已解决~
