### ISSUE TITLE
ipv6支持

### ISSUE THREAD

**Issue by styxiik** [aoyouer/selfhelp-iptables#5]
在支持ipv6环境下，程序无法拦截通过ipv6连接的请求，也无法触发包速率记录。
随着网络环境的监察检测的越发严重，以及ipv6的普及，希望能加上对ipv6的支持。

**Comment by haojie06** [comment]
这个月是没空啦，下个月如果有时间的话我是考虑重写一些iptables的部分的

**Comment by styxiik** [comment]
> 

Thx, 暂时禁用ipv6问题也不大，作为一个完善参考吧~
