### ISSUE TITLE
能否增加内网网段白名单？

### ISSUE THREAD

**Issue by o0wattson0o** [aoyouer/selfhelp-iptables#6]
内网网段白名单能自己添加吗？或者后台运行程序了，可以通过什么方式添加白名单进去，因为每次重启selfhelp-iptables，白名单都会被清空。

**Comment by haojie06** [comment]
我最近考虑重写一下这个程序，顺便让它支持配置文件

**Comment by o0wattson0o** [comment]
目前有办法可以临时解决一下吗？我自己添加iptables规则可以吗？先添加，再运行selfhelp?

**Comment by o0wattson0o** [comment]
./selfhelp-iptables start -u tmdcmcc -a yywrnhad -p 80
只保护了80端口，为什么还会无感添加IP白名单，无感添加可以关闭吗?

**Comment by haojie06** [comment]
无感添加你没设置那个trigger是不会启用的。 然后你也可以自己加iptables的规则，这个程序增加的规则都是在一条独立的链里面的，你可以自己加，不过你要先启动这个程序再自己添加，用 iptables -I INPUT 1 -m state -s 192.168.2.0/24  -j ACCEPT 把内网放行的规则在第一行插入

**Comment by o0wattson0o** [comment]
感谢大佬

**Comment by fengguowudi** [comment]
> 我最近考虑重写一下这个程序，顺便让它支持配置文件

如何了（）

**Comment by haojie06** [comment]
> > 我最近考虑重写一下这个程序，顺便让它支持配置文件
> 
> 如何了（）

最近工作上的事情挺多的所以没做，抱歉了😥。不过我考虑用rust写一下来练练手。

**Comment by o0wattson0o** [comment]
cd /root
nohup ./selfhelp-iptables start -u ***@***.*** -a ***@***.*** -p 22,2890,2891,8986,3306 -r d &gt; cc.log 2&gt;&amp;1 &amp;


# 延迟5秒执行添加白名单IP
ping 127.0.0.1 -c 5
# 增加VOS及内网IP段
iptables -I SELF_WHITELIST -s 120.77.171.64 -j ACCEPT
iptables -I SELF_WHITELIST -s 172.29.89.0/24 -j ACCEPT







我只封堵了这几个端口，其他端口应该是默认放行的，但是我用起来，还是访问不了哦，关键是我的程序还是动态端口的，没有办法说指定白名单端口为0-65535吗？


wattson
***@***.***



&nbsp;

**Comment by haojie06** [comment]
iptables -I SELF_WHITELIST 理论上是可行的，你可以先看看 iptables -vnL SELF_WHITELIST

**Comment by haojie06** [comment]
https://github.com/haojie06/selfhelp-iptables/releases/tag/2.4.0 试试这个，看看新版本的readme的说明

**Comment by o0wattson0o** [comment]
防火墙也很占系统资源吗？我开启了白名单经常就是CPU100%
nohup ./selfhelp-iptables start -u BJwpXtgVUvyHDUbe -a ***@***.*** -p 22 -p 8000 -p 2660 -p 2661 -p 3306 --allow 47.106.222.223
/32 d &gt; cc.log 2&gt;&amp;1 &amp;


保护了22，8000，2660，2661，3306


&nbsp;


wattson
***@***.***



&nbsp;

**Comment by haojie06** [comment]
我这两天检查一下看看，如果你提供一下cpu100%的时候top命令的截图就更好了。
