### ISSUE TITLE
--trigger [counts]/[seconds] 请教

### ISSUE THREAD

**Issue by aswez** [aoyouer/selfhelp-iptables#8]
本人小白，请问 --trigger [counts]/[seconds] 使用方式：

我执行命令 ```./selfhelp-iptables start -u jdsxSjfimoPsx -a ooppee3A --trigger 9/3 -p 13292``` 后:

在浏览器通过访问 google.com 并且在三秒内刷新九次以上，会自动添加当前 IP 白名单吗？

因为我通过上述方式发现没有添加白名单，请问怎么使用？

**Comment by haojie06** [comment]
是的，不过不是刷新，这个是收到包的次数，比如收到一个开始连接的syn包，如果你运行程序后能看见探测记录输出，那么每次输出就是一次。如果你发现没添加，那可能是发送包的次数不够快。

**Comment by aswez** [comment]
好的，谢谢。
我发现通过浏览器访问 google.com，发包频率在 3 秒 4-5 次左右，有其他频率更快的方法吗？因为如果 ```--trigger 5/3 ``` 可能会误判其他异常访问。
